baseURL = "http://abbieschenk.com/"
languageCode = "en-ca"
title = "Abbie Schenk"
theme = "hugo-theme-abbieschenk"
disqusShortname = "abbieschenk"

copyright = "All work is Copyright of © Abbie Schenk unless otherwise identified."

[author]
  name = "Abbie Schenk"

[permalinks]
  post = "/:filename/"

[taxonomies]
 tags = "tags"

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Projects"
    url = "/projects/"
    weight = 2
  [[menu.main]]
    name = "Posts"
    url = "/posts/"
    weight = 3

  [[menu.social]]
    name = "Instagram"
    pre = "instagram"
    url = "https://instagram.com/abbieschenk"
    weight = 1
  [[menu.social]]
    name = "Twitter"
    pre = "twitter"
    url = "https://twitter.com/abbieschenk"
    weight = 2
  [[menu.social]]
    name = "LinkedIn"
    pre = "linkedin"
    url = "https://www.linkedin.com/in/abbie-schenk/"
    weight = 3
  [[menu.social]]
    name = "GitHub"
    pre = "github"
    url = "https://github.com/abbieschenk"
    weight = 4
  [[menu.social]]
    name = "RSS"
    pre = "rss"
    url ="/index.xml"
    weight = 5

[params]
  dateFormat = "Jan 2, 2006"
  accentColor = "#53705C"
  cloudinary = "abbieschenk"
  twitter = "@abbieschenk"

[markup.goldmark.renderer]
  unsafe= true